### ISSUE TITLE
2.2.3 逻辑错误

### ISSUE THREAD

**Issue by Kros-ZERO** [CoopEdu2022/Gary#1]
https://github.com/CoopEdu2022/Gary/blob/b49b7ae7dd8f58341e3575408b0bdf01ebd874ff/U1-L2/2.2.3.py#L13-L15

这里逻辑不对，导致 age = 20 的时候没有任何输出，想一下

**Comment by GaryZhangstu** [comment]
好的👌

**Comment by GaryZhangstu** [comment]
我尝试改了一下可以还是不可以😭😂😭😂😭
