### ISSUE TITLE
3.1.6 这不是妥妥的死循环

### ISSUE THREAD

**Issue by Kros-ZERO** [CoopEdu2022/Gary#4]
https://github.com/CoopEdu2022/Gary/blob/fbd160970ffaa6a22cd521f6484b4044b07d48cc/U1-L3/3.1.6.py#L3-L12

请问我如何跳出循环计算平均分？-5 of 10

**Comment by GaryZhangstu** [comment]
确实😁😁😁😁😁

**Comment by GaryZhangstu** [comment]
改完了😶‍🌫️😶‍🌫️
